*THEME : Fortress*
*LIMITATION : Player must control multiple entities*

Hmmm, well does this mean at the same time or at some point?

I can't think of many games that allow multiple entity control unless it's
a CRPG or strategy game but that's different...

I deal Idea B much easier to make and much faster to make
so I'll probably make idea B the game... It's like a tower defense
but you do it yourself.

* Idea A: Timesplit adventurers
  Well let's see, maybe we can do a "time-split" sort of dealie and still have
  it work.

  Have like 3 or 4 unique heroes and split a different interval of time between them
  in order. This might make the game a huge PITA, or it could be interesting.

  We'll explain it away with some weird entanglement spell.

  Lots of powerups will definitely be needed to make the game not feel like ass.

  So like a bunch of adventurers show up into a castle to conquer the big baddie,
  we'll have like 4 levels or something of moderate size to be not horrible.

  They are :

  THE KNIGHT : Heavy defense, okay attack, not much else ,
  can break doors
  (15 seconds)

  THE CLERIC : Moderate defense, bad attack, but can heal themself and the rest
  (15 seconds)

  THE WIZARD : Low defense, faster, good attack,
  also has a spell that can allow the unlocking shortcuts by controlling the
  castle's obstacles (opening a draw bridge or shortcut or some loot)
  (10 seconds)

  THE BARBARIAN : no defense, very fast, good attack, higher jump
  (10 seconds)

  There will be powerups to :

  DELAY THE "MIND" SWAP (+5 seconds)
  FORCE THE "MIND" SWAP (to another character of choice)

  and then your standard fair of hp and stuff like that.

  To make the game less annoying it will have to fast paced, and the stuff
  might have to be designed around having multiple entities (like puzzles that
  require a person on the other side or something)

  Basically the game allows you to control multiple entities but only one at a time,
  which should be fair. I can't really see anything other than a party based game for that.
* Idea B: Security Defense...
  This is like a tower defense... Except you have to micro-manage everything.
  Good luck!

  You play as an autonomous security system fighting against a
  couple of thieves.
  
  You place units at the time between rounds spread across a few flights of level.
  During the round you have to jump around each flight and control each unit in the
  room and some traps inside a room.
  
  The difficulty comes in micro managing each unit. To make the game more convenient
  you only have a max of 10 units per segment (to allow for arrow key selection that
  doesn't take forever and so you can use the numpad or something like that).
  
  You have to last up to like 10 rounds let's just say? Or make it infinite?
  
  Why did I make ANOTHER tower-defense ish game after I did one for LD46 anyways?
  
  IDK but I guess this works.
  
  To make the game not completely unfair I'll probably allow 6 - 7 enemies per flight,
  
  enemies:
  runner : moderate speed, average health, this is the average enemy, low damage
  hacker : high speed, low health, very high damage and can remotely damage things (ceiling turrets no work.)
  emp-hacker : medium speed, medium health, no damage but stuns devices in a room
  muscle man : medium speed, medium-high health, medium damage, no knockback on hit
  ninja : high speed, low health, medium damage, is nearly invisible (how do I show this? particles?)
  rogue security bot : robot, very high health, medium damage, very slow
  
  boss enemies: (probably not including)
  ED 209 - like : A super security bot basically, will ignore passively damage rooms, and can open doors
  Super Muscle Man : (arnold?) Just absurdly high health is all.

  ascii mock up looks like this
  
  (maybe the rooms should have teleporters to allow enemies to move
  between flights?)
  
  +HP BAR +CASH +POWER
  |   |   |   | --DANGER ZONE
  |---|---|---|
  |   |   |   | --DANGER ZONE
  |---|---|---|
  |   |   |   | --DANGER ZONE
  |---|---|---|
  
  The power bar will allow you to control certain room specific entities.
  Like a gas chamber, slow chamber, radiation chamber, and timestop, 
  each section has the ability to wall off themselves temporarily for like 5 seconds to allow breathing room.
  
  controls are like:

  WASD : Movement between rooms
  ARROW KEYS, NUMBER KEYS, MOUSE PICK : Movement between units
  ESC : Pause / Menu
  ENTER : CONFIRM next round?
